server:
  port: 8092

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Keycloak setup at ~/Dev/oidc/keycloak-17.0.1:
          jwk-set-uri: http://localhost:8180/realms/spring-as/protocol/openid-connect/certs
